"""
Enhanced OCR Engine - Auto-generated by setup script
"""
from app.document_processor.ocr_engine_enhanced import EnhancedOCREngine

# Re-export for compatibility
OCREngine = EnhancedOCREngine

__all__ = ['OCREngine', 'EnhancedOCREngine']
