"""
Enhanced Table Extractor - Auto-generated by setup script
"""
from app.document_processor.table_extractor_enhanced import EnhancedTableExtractor

# Re-export for compatibility
TableExtractor = EnhancedTableExtractor

__all__ = ['TableExtractor', 'EnhancedTableExtractor']
